// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/captv89/parOverview/model"

func tabularScript(data []model.GeoParReport) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_tabularScript_d880`,
		Function: `function __templ_tabularScript_d880(data){console.log(data);
	const gridOptions = {
		rowData: data,
		pagination: true,
		paginationPageSize: 500,
		paginationPageSizeSelector: [200, 500, 1000],
		columnDefs: [
			{ headerName: "Date", field: "Date", sortable: true, filter: true, floatingFilter: true },
			{ headerName: "Ship Name", field: "ShipName", sortable: true, filter: true, floatingFilter: true },
			{ headerName: "Ship Type", field: "ShipType", sortable: true, filter: true, floatingFilter: true },
			{ headerName: "IMO", field: "IMONo", sortable: true, filter: true, floatingFilter: true },
			{ headerName: "Area", field: "Area", sortable: true, filter: true, floatingFilter: true },
			{ headerName: "Latitude", field: "Latitude", sortable: true, filter: true, floatingFilter: true },
			{ headerName: "Longitude", field: "Longitude", sortable: true, filter: true, floatingFilter: true },
			{ headerName: "IncidentDetails", field: "IncidentDetails", sortable: true, filter: true, floatingFilter: true, autoHeight:true, wrapText:true },
		],
	};


	const myGridElement = document.querySelector('#myGrid');
	agGrid.createGrid(myGridElement, gridOptions);
}`,
		Call:       templ.SafeScript(`__templ_tabularScript_d880`, data),
		CallInline: templ.SafeScriptInline(`__templ_tabularScript_d880`, data),
	}
}

func TabularBody(data []model.GeoParReport) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-full\"><div id=\"myGrid\" class=\"ag-theme-quartz-dark h-5/6 w-full\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = tabularScript(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
